// Run with playwright-cli in an isolated sketchpad tab. These are synthetic drawings.
async (page) => {
  const checks = [];
  const assert = (value, label) => { if (!value) throw new Error(label); checks.push(label); };
  const button = name => page.getByRole('button', {name, exact:true});
  const canvas = page.getByLabel('Drawing canvas. Draw with a mouse, finger, or stylus.', {exact:true});
  const pixel = (x, y) => canvas.evaluate((el, [x,y]) => [...el.getContext('2d').getImageData(Math.min(el.width-1,Math.round(x*el.width/1200)),Math.min(el.height-1,Math.round(y*el.height/900)),1,1).data].join(), [x,y]);
  const snapshot = () => canvas.evaluate(el => el.toDataURL());
  const white = '255,255,255,255', blue = '75,92,219,255', coral = '223,97,85,255', charcoal = '37,41,51,255';
  const draw = async points => {
    const r = await canvas.boundingBox();
    await page.mouse.move(r.x + points[0][0] * r.width / 1200, r.y + points[0][1] * r.height / 900);
    await page.mouse.down();
    for (const [x,y] of points.slice(1)) await page.mouse.move(r.x + x * r.width / 1200, r.y + y * r.height / 900, {steps:8});
    await page.mouse.up();
  };
  const click = async (x,y) => { const r = await canvas.boundingBox(); await page.mouse.click(r.x + x * r.width / 1200, r.y + y * r.height / 900); };
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({width:1280,height:720});
  await page.reload();
  await button('Rectangle').click();
  await draw([[100,100],[500,400]]);
  await button('Ellipse').click();
  await draw([[650,100],[1050,400]]);
  const outlines = await snapshot();
  await page.keyboard.press('f');
  assert(await button('Fill').getAttribute('aria-pressed') === 'true', 'F selects the fill bucket');
  await button('Blue').click();
  assert(await button('Fill').getAttribute('aria-pressed') === 'true', 'Selecting ink keeps the fill bucket active');
  await click(300,250);
  assert(await pixel(300,250) === blue, 'Fill colors the selected rectangle interior');
  assert(await pixel(30,30) === white && await pixel(850,250) === white, 'Fill leaves exterior and separate enclosed areas unchanged');
  assert(await pixel(100,250) === charcoal, 'Fill preserves the shape outline');
  const filled = await snapshot();
  await button('Undo').click();
  assert(await snapshot() === outlines, 'One Undo restores the exact unfilled drawing');
  await button('Redo').click();
  assert(await snapshot() === filled, 'Redo restores the exact filled drawing');
  await click(300,250);
  await button('Undo').click();
  assert(await snapshot() === outlines, 'Filling with the same color adds no undo step');
  await button('Redo').click();
  await button('Coral').click();
  await click(850,250);
  assert(await pixel(850,250) === coral && await pixel(300,250) === blue, 'Ellipse can be filled independently');
  await click(300,250);
  assert(await pixel(300,250) === coral, 'A filled area can be recolored');
  await button('Blue').click();
  await click(20,20);
  assert(await pixel(1199,899) === blue && await pixel(850,250) === coral, 'Background fill reaches canvas edges without crossing closed outlines');
  const beforeStroke = await snapshot();
  await button('Pen').click();
  await button('Charcoal').click();
  await draw([[100,600],[500,600]]);
  assert(await pixel(300,600) === charcoal && await pixel(300,250) === coral, 'Drawing after a fill preserves the filled areas');
  await button('Undo').click();
  assert(await snapshot() === beforeStroke, 'Undo of a later stroke preserves fill history');
  await button('Clear').click();
  await button('Undo').click();
  assert(await snapshot() === beforeStroke, 'Undo Clear restores the filled artwork');
  const downloading = page.waitForEvent('download');
  await button('Download PNG').click();
  const downloaded = await downloading;
  await downloaded.saveAs('output/playwright/canvas2imagegen-fill-fixture.png');
  assert(await downloaded.failure() === null && await snapshot() === beforeStroke, 'PNG export succeeds and preserves the filled artwork');

  await page.reload();
  await page.locator('#size').fill('2');
  await draw([[150,650],[500,450],[800,750],[150,650]]);
  await button('Fill').click();
  await button('Blue').click();
  await click(480,610);
  assert(await pixel(480,610) === blue && await pixel(20,20) === white, 'Thin closed freehand outline contains the fill');
  const original = await canvas.evaluate(el => ({width:el.width,height:el.height}));
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(() => document.querySelector('canvas').height === 1200);
  const resized = await canvas.evaluate(el => ({width:el.width,height:el.height}));
  const scale = Math.min(resized.width/original.width,resized.height/original.height);
  const seedX = ((resized.width-original.width*scale)/2 + 480*original.width/1200*scale)/resized.width*1200;
  const seedY = ((resized.height-original.height*scale)/2 + 610*original.height/900*scale)/resized.height*900;
  const freehand = await snapshot();
  await button('Coral').click();
  const r = await canvas.boundingBox();
  const cdp = await page.context().newCDPSession(page);
  await cdp.send('Input.dispatchTouchEvent', {type:'touchStart', touchPoints:[{x:r.x+seedX*r.width/1200,y:r.y+seedY*r.height/900}]});
  await cdp.send('Input.dispatchTouchEvent', {type:'touchEnd', touchPoints:[]});
  await cdp.detach();
  assert(await pixel(seedX,seedY) === coral && await pixel(20,20) === white, 'Touch fills the correct region after responsive resize');
  await button('Undo').click();
  assert(await snapshot() === freehand, 'Touch fill creates exactly one history entry');
  await page.screenshot({path:'output/playwright/canvas2imagegen-fill-mobile.png'});
  await page.setViewportSize({width:320,height:720});
  assert(await page.evaluate(() => document.documentElement.scrollWidth === innerWidth), 'Six tools fit the narrow mobile layout');

  await page.reload();
  await button('Fill').click();
  await button('Blue').click();
  await click(0,0);
  assert(await pixel(0,0) === blue && await pixel(1199,899) === blue, 'Fill works on a blank canvas including corner pixels');
  assert(await button('Copy image').isEnabled() && await button('Download PNG').isEnabled(), 'A background fill can be exported');
  await button('Undo').click();
  assert(await button('Copy image').isDisabled(), 'Undo of the only fill returns to an empty canvas');
  assert(errors.length === 0, 'No browser runtime errors during fill operations');
  return {passed:checks.length,checks};
}
